# Generated by Django 2.2.3 on 2019-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20190720_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='pics')),
                ('movie_id', models.IntegerField()),
                ('genres', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
