# Generated by Django 2.2.3 on 2019-08-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('user_id', models.ImageField(upload_to='')),
                ('ratings', models.ImageField(upload_to='')),
            ],
        ),
    ]
